[workspace.package]
authors = "{{authors}}"
categories = []
description = ""
edition = "2021"
homepage = "https://github.com/${{owner}}/${{crate_name}}/wikis"
license = "Apache-2.0"
repository = "https://github.com/${{owner}}/${{crate_name}}"
readme = "README.md"
version = "0.0.0" # TODO - Update cargo package version

[workspace]
default-members = [
    "${{crate_name}}"
]
exclude = [ ]
members = [
    "${{crate_name}}",
]
resolver = "2"

[workspace.dependencies]


[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
panic = "unwind"
rpath = false
opt-level = 0
overflow-checks = true

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = false
panic = "unwind"
rpath = false
opt-level = "z"
overflow-checks = false
