[template]
cargo_generate_version = ">=0.19"


[placeholders.origin]
default = "{username}"
prompt = "Git origin (username)"
type = "string"

[placeholders.spdx]
choices = ["Apache-2.0", "MIT", "Unlicense"]
default = "Apache-2.0"
prompt = "license (SPDX)"
type = "text"

[placeholders]
app_name = { default = "${crate_name}-app", prompt = "app name:", type = "string" }
description = { default = "", prompt = "description:", type = "string" }
github = { default = "", prompt = "GitHub Username:", type = "string" }
owner = { default = "{username}", prompt = "Codeowner", type = "string" }
use_git = { default = true, prompt = "Initialize Git repository?", type = "boolean" }

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs"]

[conditional.'crate_type == "bin"']
include = ["src/bin/main.rs"]
