[workspace]
default-members = [
    "{{ project-name }}"
]

exclude = [ ]

members = [
    "{{ project-name }}",
]

resolver = "2"

[workspace.dependencies]
anyhow = "1"
lazy_static = "1"
paste = "1"
smart_default = "0.7"
thiserror = "2"

[workspace.dependencies.'cfg(target_arch = "wasm32")']
wasm-bindgen = "0.2"

[workspace.package]
authors = ["{{ authors }}",]
categories = [ ]
description = "{{ description }}"
edition = "2021"
homepage = "https://{{ provider }}/{{ handle }}/{{ project-name }}/wiki"
keywords = [ ]
license = "{{ license }}"
readme = "README.md"
repository = "https://{{ provider }}/{{ handle }}/{{ project-name }}.git"
version = "0.0.0"

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
panic = 'unwind'
rpath = false
opt-level = 0
overflow-checks = true

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = true
panic = 'abort'
rpath = false
opt-level = "z"
overflow-checks = false
