[workspace]
default-members = [
    "{{ project-name }}"
]

exclude = [ ]

members = [
    "{{ project-name }}",
]

resolver = "3"

[workspace.dependencies]
anyhow = { version = "1" }
lazy_static = { version = "1" }
paste = { version = "1" }
serde = { default-features = false, version = "1" }
serde_derive = { version = "1" }
serde_json = { version = "1" }
smart_default = { version = "0.7" }
thiserror = { default-features = false, version = "2" }

[workspace.package]
authors = ["{{ authors }}",]
categories = [ ]
description = "{{ description }}"
edition = "{{ edition }}"
homepage = "https://{{ provider }}/{{ alias }}/{{ project-name }}/wiki"
keywords = [ ]
license = "{{ license }}"
readme = "README.md"
repository = "https://{{ provider }}/{{ alias }}/{{ project-name }}.git"
version = "0.0.0"

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
panic = 'unwind'
rpath = false
opt-level = 0
overflow-checks = true

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = true
panic = 'abort'
rpath = false
opt-level = "z"
overflow-checks = false
