[template]
cargo_generate_version = ">=0.9.0"

[placeholders.git]
description = "The path to the desired git"
prompt = "Optionally, provide the path to the desired git"
type = "string"

[placeholders.description]
prompt = "A short description of the project"
type = "string"
