name: cargo-publish

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  repository_dispatch:
    types: [ publish, cargo-publish ]
  workflow_dispatch:

jobs:
  crates-io:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
    environment:
      name: crates-io
    outputs:
      url:  ${{ steps.results.outputs.url }}
    permissions:
      contents: read
      deployments: write
      packages: write
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package:
          - {{ project-name }}-core
          - {{ project-name }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          lfs: true
          ref: ${{ github.ref }}
          repository: ${{ github.repository }}
      -
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      -
        name: Publish (${{ matrix.package }})
        id: publish
        run: cargo publish --locked --package ${{ matrix.package }}
      -
        name: Set output(s)
        id: results
        run:
          echo "url=https://crates.io/crates/${{ matrix.package }}" >> "$GITHUB_OUTPUT"
