# This workflow is used to benchmark a Rust project
name: cargo-bench
# The workflow may be manually triggered and is run automatically when:
# - a pull request is closed on the default branch (main/master)
# - a release is published
# - a repository_dispatch event with the type "cargo-bench" is received

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches: [main, master]
    tags: [latest, v*.*.*, "*-nightly"]
  repository_dispatch:
    types: [cargo-bench]
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Whether to benchmark the entire Cargo workspace (true/false)'
        required: false
        default: true
        type: boolean
      package:
        description: 'The Cargo workspace or package to benchmark (e.g., workspace or my-package)'
        required: false
        default: 'workspace'
      target:
        description: 'The target triple to benchmark (e.g., x86_64-unknown-linux-gnu)'
        required: false
        default: 'x86_64-unknown-linux-gnu'
      features:
        description: 'The Cargo features to enable during benchmarking (comma-separated list)'
        required: false
        default: 'full'
      toolchain:
        description: 'The Rust toolchain to use (e.g., stable, beta, nightly, or a specific version)'
        required: false
        default: 'stable'
        type: choice
        options: [stable, nightly, beta]


env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUST_TARGET: ${{ github.event.client_payload.target || github.event.inputs.target || 'x86_64-unknown-linux-gnu' }}
  RUST_TOOLCHAIN: ${{ github.event.client_payload.toolchain || github.event.inputs.toolchain || 'stable' }}
  FEATURE_FLAGS: ${{ github.event.client_payload.features || github.event.inputs.features || 'full' }}

permissions:
  contents: write
  checks: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.artifacts.outputs.artifact-id }}
      digest: ${{ steps.artifacts.outputs.artifact-digest }}
      url: ${{ steps.artifacts.outputs.artifact-url }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: ${{ github.event.client_payload.package || github.event.inputs.package || 'workspace' }}
            target: ${{ github.env.RUST_TARGET }}
            features: ${{ github.env.FEATURE_FLAGS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.ref  || github.ref }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-criterion
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-criterion
      - name: Benchmark (${{ matrix.target }})
        if: matrix.package == 'workspace'
        run: cargo criterion --benches --locked --verbose --workspace --features ${{ matrix.features }} --target ${{ matrix.target }}
      - name: Benchmark ${{ matrix.package }} (${{ matrix.target }})
        if: matrix.package != 'workspace'
        run: cargo criterion --benches --locked --verbose --package ${{ matrix.package }} --features ${{ matrix.features }} --target ${{ matrix.target }}
      - name: Upload the benchmarks
        id: artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Benchmark Report (${{ github.run_id }})
          if-no-files-found: error
          overwrite: true
          path: target/criterion/
