name: crates-io

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: read
  packages: write

jobs:
  publish:
    env:
      CRATE: ${{ github.event.repository.name }}
    environment:
      name: release
      url: https://crates.io/crates/${{ env.CRATE }}
    runs-on: ubuntu-latest
    needs: core
    steps:
      - uses: actions/checkout@v4
      - 
        name: publish (${{env.CRATE}})
        run: cargo publish --all-features -v -p ${{ env.CRATE }}