name: rust

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  CRATE_BASENAME: ${{ github.event.repository.name }}

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ v*.*.* ]
  release:
    types: [ created ]
  repository_dispatch:
    types: [ rust ]
  schedule:
    - cron: "30 21 * * 0" # Every Sunday at 9:30pm UTC
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        toolchain: [ stable, nightly ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup (rustup)
        run: |
          rustup default ${{ matrix.toolchain }}
          rustup update
      - name: build (workspace)
        run: cargo build --all-features -r -v --workspace
      - name: test (workspace)
        run: cargo test --all-features -v --workspace
      - name: bench (workspace)
        if: matrix.toolchain == 'nightly'
        run: cargo bench -F full -v --workspace
      - name: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/release
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-${{ matrix.toolchain }}-
            ${{ runner.os }}-cargo-
